# argocd/currencyconverter.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # The name you see on the Argo CD card
  name: currencyconverter-production 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aashwin11backsup/AWS-EKS-argoCD-WORKFLOW.git'
    targetRevision: https-check

    path: k8s/overlays/production
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true