apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: argocd

patches:
- patch: |-
    - op: add
      path: /spec/rules
      value:
        - host: argocd.trialphase.shop
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: argocd-server
                    port:
                      number: 80
    - op: add
      path: /spec/tls
      value:
        - hosts:
            - argocd.trialphase.shop
          secretName: dummy-tls-secret-trail-1
  target:
    kind: Ingress
    name: shared-main-ingress
